# Generated by Django 5.1.6 on 2025-03-19 19:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_profiles/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar ID must be a 12-digit number.', regex='^\\d{12}$')]),
        ),
        migrations.AddConstraint(
            model_name='farmer',
            constraint=models.UniqueConstraint(fields=('aadhar_id',), name='unique_aadhar_id'),
        ),
    ]
